Repository docker/compose-cli, pull requests merged in 2021-08, with the labels that each got.

#1990 Fix formatting bug in ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: ci

#2003 Fix typo
  docs/ecs-architecture.md
Labels: documentation

#2009 Fix typo
  docs/ecs-architecture.md
Labels: documentation

#2019 Bump compose-go
  go.mod
  go.sum
Labels: documentation

#2041 publish cross platform artifacts for PRs
  .github/workflows/artifacts.yml
  .github/workflows/pending_answered.yml
  .github/workflows/pr-closed.yml
Labels: ci

#2054 remove all references to cli from compose.v2 cmd package
  aci/login/client.go
  cli/cmd/context/ls.go
  cli/cmd/context/rm.go
  cli/cmd/inspect.go
  cli/cmd/kill.go
  cli/cmd/ps.go
  cli/cmd/rm.go
  cli/cmd/secrets.go
  cli/cmd/start.go
  cli/cmd/stop.go
  cli/cmd/version.go
  cli/cmd/volume/command.go
  cli/cmd/volume/list.go
  cli/main.go
  cmd/compose/compose.go
  cmd/compose/images.go
  cmd/compose/list.go
  cmd/compose/logs.go
  cmd/compose/ps.go
  cmd/compose/up.go
  cmd/compose/version.go
  cmd/formatter/colors.go
  cmd/formatter/consts.go
  cmd/formatter/formatter.go
  cmd/formatter/formatter_test.go
  cmd/formatter/json.go
  cmd/formatter/logs.go
  cmd/formatter/multierrformat.go
  cmd/formatter/pretty.go
  cmd/main.go
  docs/yaml/main/generate.go
  ecs/sdk.go
  internal/variables.go
Labels: aci, cli, documentation
